=== KarajuSs/PolskaGRA/data/conf/creatures.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>


<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="stendhal" xmlns:tns="http://www.example.org/creatures"
	elementFormDefault="qualified" xmlns:Q2="stendhal">

	<xsd:element name="creatures" type="Q2:CreaturesType"></xsd:element>

	<xsd:complexType name="CreaturesType">
		<xsd:sequence>
			<xsd:element name="creature" type="Q2:CreatureType"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="CreatureType">
		<xsd:sequence>
			<xsd:element name="type" type="Q2:Type" minOccurs="1" />
			<xsd:element name="hidden" type="xsd:string" minOccurs="0" />
			<xsd:element name="description" type="xsd:string" minOccurs="0" />
			<xsd:element name="attributes" type="Q2:Attributes" minOccurs="1" />
			<xsd:element name="level" type="Q2:Level" minOccurs="1" />
			<xsd:element name="experience" type="Q2:Experience"	minOccurs="1" />
			<xsd:element name="respawn" type="Q2:Respawn" />
			<xsd:element name="blood" type="Q2:Blood" minOccurs="0" />
			<xsd:element name="corpse" type="Q2:Corpse" />
			<xsd:element name="drops" type="Q2:Drops" minOccurs="0" />
			<xsd:element name="slots" type="Q2:Slots" minOccurs="0" />
			<xsd:element name="equips" type="Q2:Equips" minOccurs="0" />
			<xsd:element name="abilities" type="Q2:Abilities" minOccurs="0"/>
			<xsd:element name="ai" type="Q2:Ai" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="condition" type="xsd:string" use="optional" />
	</xsd:complexType>

	<xsd:complexType name="Item">
		<xsd:attribute name="value" type="xsd:string" />
		<xsd:attribute name="quantity" type="xsd:string" />
		<xsd:attribute name="probability" type="xsd:double" />
	</xsd:complexType>

	<xsd:complexType name="Drops">
		<xsd:sequence>
			<xsd:element name="item" type="Q2:Item" minOccurs="0"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Respawn">
		<xsd:sequence>
		</xsd:sequence>
		<xsd:attribute name="value" type="xsd:positiveInteger"/>
	</xsd:complexType>
	
	<xsd:complexType name="Blood">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="Corpse">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="width" type="xsd:positiveInteger"/>
		<xsd:attribute name="height" type="xsd:positiveInteger"/>
		<xsd:attribute name="harmless" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Attributes">
		<xsd:sequence>
			<xsd:element name="atk" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="def" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="hp" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="speed" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:decimal" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="size" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="noise" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="state" type="xsd:string" />
					<xsd:attribute name="value" type="xsd:string" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Ai">
		<xsd:sequence>
			<xsd:element name="says" type="Q2:Says" minOccurs="0" />
			<xsd:element name="profile" type="Q2:Profile" minOccurs="1"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Says">
		<xsd:sequence>
			<xsd:element name="noise" type="Q2:Noise" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="sound" type="Q2:Sound" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="movement" type="Q2:Movement" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="death" type="Q2:Death" minOccurs="0"
			  maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Noise">
		<xsd:attribute name="value" type="xsd:string" />
		<xsd:attribute name="state" type="xsd:string"></xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="Sound">
		<xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Movement">
		<xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>
	
	<xsd:complexType name="Death">
	  <xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Profile">
		<xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="params" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Type">
		<xsd:attribute name="class" type="xsd:string" />
		<xsd:attribute name="subclass" type="xsd:string" />
		<xsd:attribute name="tileid" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Level">
		<xsd:attribute name="value" type="xsd:integer" />
	</xsd:complexType>

	<xsd:complexType name="Experience">
		<xsd:attribute name="value" type="xsd:integer" />
	</xsd:complexType>

	<xsd:complexType name="Slots">
		<xsd:sequence>
			<xsd:element name="slot" type="xsd:string" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Equips">
		<xsd:sequence>
			<xsd:element name="slot" type="Q2:Slot" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Abilities">
		<xsd:sequence>
			<xsd:element name="damage" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string" default="cut"/>
					<xsd:attribute name="rangedType" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="susceptibility" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string" />
					<xsd:attribute name="value" type="xsd:decimal" />
				</xsd:complexType>
			</xsd:element>
      <xsd:element name="statusattack" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:attribute name="type" type="xsd:string" />
          <xsd:attribute name="value" type="xsd:decimal" />
        </xsd:complexType>
      </xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Slot">
	    <xsd:sequence>
	    </xsd:sequence>
	    <xsd:attribute name="name" type="xsd:string" use="required" />
	    <xsd:attribute name="item" type="xsd:string" use="required" />
	    <xsd:attribute name="quantity" type="xsd:positiveInteger" />
	</xsd:complexType>

</xsd:schema>

=== KarajuSs/PolskaGRA/data/conf/creatures/pol/czarty.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../../creatures.xsd ">

	<!-- START: czart -->

	<creature name="belzebub">
		<type class="pol/czarty" subclass="czart_belzebub" tileid="pol_czarty.png:0"/>
		<description/>
		<attributes>
			<atk value="454"/>
			<def value="37"/>
			<hp value="1662"/>
			<speed value="0.9"/>
			<size value="1,1"/>
		</attributes>
		<level value="150"/>
		<experience value="5112"/>
		<respawn value="4321"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[99,599]" probability="100.0"/>
			<item value="magia płomieni" quantity="[1,44]" probability="30.0"/>
			<item value="bełt płonący" quantity="[1,19]" probability="100.0"/>
			<item value="różdżka Swaroga" quantity="[1,1]" probability="0.1"/>
			<item value="czarne rękawice" quantity="[1,1]" probability="0.001"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<noise state="idle follow fight" value="Przekroczyłeś wrota piekieł!"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="zapomniany diabeł">
		<type class="pol/czarty" subclass="czart_bezimienny" tileid="pol_czarty.png:1"/>
		<description/>
		<attributes>
			<atk value="411"/>
			<def value="31"/>
			<hp value="1541"/>
			<speed value="0.8"/>
			<size value="1,1"/>
		</attributes>
		<level value="120"/>
		<experience value="9876"/>
		<respawn value="3456"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[1410,1410]" probability="1.0"/>
			<item value="ognista tarcza" quantity="[1,1]" probability="5.0"/>
			<item value="magia deszczu" quantity="[1,11]" probability="10.0"/>
			<item value="trójząb Trzygłowa" quantity="[1,1]" probability="0.05"/>
			<item value="lazurowe rękawice" quantity="[1,1]" probability="0.01"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<noise state="idle follow fight" value="Nie wrócę do piekła! Nie!"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="lucyfer">
		<type class="pol/czarty" subclass="czart_lucyfer" tileid="pol_czarty.png:2"/>
		<description/>
		<attributes>
			<atk value="467"/>
			<def value="41"/>
			<hp value="1662"/>
			<speed value="0.9"/>
			<size value="1,1"/>
		</attributes>
		<level value="160"/>
		<experience value="6345"/>
		<respawn value="4321"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[99,299]" probability="100.0"/>
			<item value="magia płomieni" quantity="[1,22]" probability="5.0"/>
			<item value="bełt płonący" quantity="[1,14]" probability="70.0"/>
			<item value="trójząb Trzygłowa" quantity="[1,1]" probability="0.1"/>
			<item value="karmazynowe rękawice" quantity="[1,1]" probability="0.01"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<noise state="idle follow fight" value="Krwią podpisałeś cyrograf! Pożegnaj się z bliskimi!"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="mefisto">
		<type class="pol/czarty" subclass="czart_mefisto" tileid="pol_czarty.png:3"/>
		<description/>
		<attributes>
			<atk value="454"/>
			<def value="37"/>
			<hp value="1662"/>
			<speed value="0.9"/>
			<size value="1,1"/>
		</attributes>
		<level value="140"/>
		<experience value="5112"/>
		<respawn value="4321"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[11,111]" probability="100.0"/>
			<item value="ognista tarcza" quantity="[1,1]" probability="1.0"/>
			<item value="miecz ognisty" quantity="[1,1]" probability="2.0"/>
			<item value="magia płomieni" quantity="[1,11]" probability="5.0"/>
			<item value="bełt płonący" quantity="[1,10]" probability="10.0"/>
			<item value="złote rękawice" quantity="[1,1]" probability="0.001"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<noise state="idle follow fight" value="Za twe grzechy za twe zbytki, chodź do piekła boś ty brzydki!"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="czart starszy">
		<type class="pol/czarty" subclass="czart_starszy" tileid="pol_czarty.png:4"/>
		<description/>
		<attributes>
			<atk value="401"/>
			<def value="36"/>
			<hp value="654"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="111"/>
		<experience value="4141"/>
		<respawn value="1987"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[7,53]" probability="100.0"/>
			<item value="karmazynowa tarcza" quantity="[1,1]" probability="0.5"/>
			<item value="karmazynowy hełm" quantity="[1,1]" probability="0.005"/>
			<item value="piekielny sztylet" quantity="[1,1]" probability="0.0001"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<!-- END: czart -->

</creatures>

=== KarajuSs/PolskaGRA/data/conf/creatures/pol/owady.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../../creatures.xsd ">

	<!-- START: owady -->

	<creature name="chmara much">
		<type class="pol/owady" subclass="chmara_much" tileid="pol_owady.png:0"/>
		<description>Oto muchy plujki. Przyciąga je smród padliny.</description>
		<attributes>
			<atk value="1"/>
			<def value="1"/>
			<hp value="5"/>
			<speed value="0.7"/>
			<size value="1,1"/>
			<resistance value="25"/>
		</attributes>
		<level value="0"/>
		<experience value="0"/>
		<respawn value="159"/>
		<corpse name="fly"/>
		<drops/>
		<equips/>
		<ai>
			<says>
				<noise state="idle follow fight" value="Bzzzyy!"/>
				<sound value="pol-buzz"/>
			</says>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="coward"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="rój os">
		<type class="pol/owady" subclass="roj_os" tileid="pol_owady.png:1"/>
		<description>Osy żądlą boleśnie. Jeśli masz przy sobie odtrutkę to przeżyjesz.</description>
		<attributes>
			<atk value="15"/>
			<def value="30"/>
			<hp value="30"/>
			<speed value="0.8"/>
			<size value="1,1"/>
			<resistance value="50"/>
		</attributes>
		<level value="0"/>
		<experience value="5"/>
		<respawn value="283"/>
		<corpse name="fly"/>
		<drops/>
		<equips/>
		<ai>
			<says>
				<noise state="idle follow fight" value="Bzzzzzzzzzzzz!"/>
				<sound value="pol-buzz"/>
			</says>
			<profile name="poisonous" params="3,trucizna"/>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="brave"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="rój szerszeni">
		<type class="pol/owady" subclass="roj_szerszeni" tileid="pol_owady.png:2"/>
		<description>Jad szerszeni jest zabójczy. Mało kto przeżył ich atak.</description>
		<attributes>
			<atk value="45"/>
			<def value="50"/>
			<hp value="64"/>
			<speed value="0.9"/>
			<size value="1,1"/>
		</attributes>
		<level value="6"/>
		<experience value="62"/>
		<respawn value="904"/>
		<corpse name="fly"/>
		<drops/>
		<equips/>
		<ai>
			<says>
				<noise state="idle follow fight" value="Bżżżżżżżżż!"/>
				<sound value="pol-buzz"/>
			</says>
			<profile name="heal" params="1,50"/>
			<profile name="poisonous" params="9,mocna trucizna"/>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="brave"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="motylek">
		<type class="pol/owady" subclass="motylek" tileid="pol_owady.png:3"/>
		<description>O! Popatrz! Leci motylek! Nie dosięgniesz go...</description>
		<attributes>
			<atk value="1"/>
			<def value="22000"/>
			<hp value="1"/>
			<speed value="1.0"/>
			<size value="1,1"/>
			<resistance value="1"/>
		</attributes>
		<level value="1"/>
		<experience value="1"/>
		<respawn value="3000"/>
		<corpse name="fly"/>
		<drops/>
		<equips/>
		<ai>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="coward"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<!-- END: owady -->

</creatures>

=== KarajuSs/PolskaGRA/data/conf/creatures/pol/piraci.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../creatures.xsd ">

	<!-- START: pirate -->

	<creature name="pirat">
		<type class="pol/pol_piraci" subclass="pirat" tileid="pol_piraci.png:0"/>
		<description>Oto pirat. Jest już doświadczonym piratem.</description>
		<attributes>
			<atk value="233"/>
			<def value="26"/>
			<hp value="625"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="50"/>
		<experience value="3578"/>
		<respawn value="5000"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[10,120]" probability="100.0"/>
			<item value="krótki miecz" quantity="[1,1]" probability="8.5"/>
			<item value="buty kolcze" quantity="[1,1]" probability="5.5"/>
			<item value="skórzane rękawice" quantity="[1,1]" probability="12.5"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="kamrat">
		<type class="pol/pol_piraci" subclass="pirat_kamrat" tileid="pol_piraci.png:1"/>
		<description>Oto kamrat. Brał udział w wielu wydarzeniach.</description>
		<attributes>
			<atk value="247"/>
			<def value="27"/>
			<hp value="663"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="53"/>
		<experience value="3958"/>
		<respawn value="5300"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[5,160]" probability="100.0"/>
			<item value="miecz" quantity="[1,1]" probability="5.5"/>
			<item value="złota kolczuga" quantity="[1,1]" probability="11.5"/>
			<item value="skórzane rękawice" quantity="[1,1]" probability="8.5"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="marynarz">
		<type class="pol/pol_piraci" subclass="pirat_marynarz" tileid="pol_piraci.png:2"/>
		<description>Oto marynarz. Brał udział w wielu abordażach.</description>
		<attributes>
			<atk value="252"/>
			<def value="28"/>
			<hp value="675"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="54"/>
		<experience value="4089"/>
		<respawn value="5400"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[15,150]" probability="100.0"/>
			<item value="skórzane wzmocnione rękawice" quantity="[1,1]" probability="10.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="krwawy pirat">
		<type class="pol/pol_piraci" subclass="pirat_krwawy" tileid="pol_piraci.png:3"/>
		<description>Oto krwawy pirat. Jest osobą bardzo znaną oraz poważaną przez resztę załogantów.</description>
		<attributes>
			<atk value="266"/>
			<def value="29"/>
			<hp value="713"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="57"/>
		<experience value="4493"/>
		<respawn value="5700"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[20,180]" probability="100.0"/>
			<item value="tarcza płytowa" quantity="[1,1]" probability="3.0"/>
			<item value="maczeta" quantity="[1,1]" probability="4.0"/>
			<item value="hełm kolczy" quantity="[1,1]" probability="6.5"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="wilk morski">
		<type class="pol/pol_piraci" subclass="pirat_wilk_morski" tileid="pol_piraci.png:4"/>
		<description>Oto wilk morski. Jego sława wykracza poza organizację.</description>
		<attributes>
			<atk value="275"/>
			<def value="30"/>
			<hp value="738"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="59"/>
		<experience value="4773"/>
		<respawn value="5900"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[10,80]" probability="100.0"/>
			<item value="buty kolcze" quantity="[1,1]" probability="12.0"/>
			<item value="skórzane twarde rękawice" quantity="[1,1]" probability="5.5"/>
			<item value="sztylet" quantity="[1,1]" probability="9.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="kapitan piratów">
		<type class="pol/pol_piraci" subclass="pirat_kapitan" tileid="pol_piraci.png:5"/>
		<description>Oto  kapitan piratów. Posiada własną łajbę. Podlegają mu wszyscy oficerowie, podoficerowie oraz załoga jego statku.</description>
		<attributes>
			<atk value="285"/>
			<def value="31"/>
			<hp value="763"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="61"/>
		<experience value="5060"/>
		<respawn value="6100"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[25,220]" probability="100.0"/>
			<item value="buty kolcze" quantity="[1,1]" probability="12.5"/>
			<item value="spodnie kolcze" quantity="[1,1]" probability="3.5"/>
			<item value="złota kolczuga" quantity="[1,1]" probability="8.5"/>
			<item value="sztylet" quantity="[1,1]" probability="9.5"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="kwatermistrz">
		<type class="pol/pol_piraci" subclass="pirat_kwatermistrz" tileid="pol_piraci.png:6"/>
		<description>Oto kwatermistrz. Dba o zaopatrzenie, prowadzi również spis ładunku i zajmuje się podziałem łupu.</description>
		<attributes>
			<atk value="299"/>
			<def value="32"/>
			<hp value="800"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="64"/>
		<experience value="5505"/>
		<respawn value="6400"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[5,30]" probability="100.0"/>
			<item value="maczeta" quantity="[1,1]" probability="6.5"/>
			<item value="katana" quantity="[1,1]" probability="7.0"/>
			<item value="spodnie kolcze" quantity="[1,1]" probability="5.0"/>
			<item value="hełm kolczy" quantity="[1,1]" probability="4.5"/>
			<item value="tarcza płytowa" quantity="[1,1]" probability="2.0"/>
			<item value="złote rękawice" quantity="[1,1]" probability="0.001"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<!-- END: pirate-->

</creatures>

=== KarajuSs/PolskaGRA/data/conf/creatures/pol/ptaki_wielkie.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../../creatures.xsd ">

	<!-- START: ptaki wielkie -->

	<creature name="orzeÅ‚ gigant">
		<type class="pol/ptaki_wielkie" subclass="orzel_gigant" tileid="pol_ptaki_wielkie.png:0"/>
		<description/>
		<attributes>
			<atk value="4300"/>
			<def value="140"/>
			<hp value="5000"/>
			<speed value="1.0"/>
			<size value="2,2"/>
			<resistance value="1"/>
		</attributes>
		<level value="270"/>
		<experience value="280000"/>
		<respawn value="259200"/>
		<corpse name="giant_knight"/>
		<drops>
			<item value="udko" quantity="[11,24]" probability="100.0"/>
			<item value="jajo" quantity="[1,2]" probability="10.0"/>
		</drops>
		<equips/>
		<ai>
			<says>
			</says>
			<profile name="brave"/>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="lifesteal" params="0.05"/>
			<profile name="heal" params="10,25"/>
			<profile name="attack weakest"/>
		</ai>
	</creature>

	<!-- END: ptaki wielkie -->

</creatures>

=== KarajuSs/PolskaGRA/data/conf/creatures/stendhal/oni.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../../creatures.xsd ">

	<!-- START: oni -->

	<creature name="oni wojownik">
		<type class="stendhal/oni" subclass="oni_warrior" tileid="oni.png:0"/>
		<description>Oto oni wojownik. Jego fioletowy kolor skóry nie powinien uśpić twojej czujności!</description>
		<attributes>
			<atk value="499"/>
			<def value="77"/>
			<hp value="500"/>
			<speed value="0.9"/>
			<size value="1,1"/>
		</attributes>
		<level value="67"/>
		<experience value="3660"/>
		<respawn value="2000"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[10,50]" probability="90.0"/>
			<item value="spodnie cieni" quantity="[1,1]" probability="0.8"/>
			<item value="buty cieni" quantity="[1,1]" probability="1.0"/>
			<item value="tarta" quantity="[1,2]" probability="5.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="oni łucznik">
		<type class="stendhal/oni" subclass="oni_archer" tileid="oni.png:1"/>
		<description>Oto oni łucznik. Jego strzały będą wszędzie cię ścigać, aby chronić jego królową!</description>
		<attributes>
			<atk value="511"/>
			<def value="77"/>
			<hp value="600"/>
			<speed value="0.7"/>
			<size value="1,1"/>
		</attributes>
		<level value="72"/>
		<experience value="4000"/>
		<respawn value="2300"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[10,70]" probability="100.0"/>
			<item value="złote spodnie" quantity="[1,1]" probability="2.0"/>
			<item value="strzała złota" quantity="[8,15]" probability="5.0"/>
			<item value="złote buty" quantity="[1,1]" probability="2.0"/>
		</drops>
		<equips>
			<slot name="lhand" item="strzała płonąca" quantity="10000"/>
			<slot name="rhand" item="klejony łuk" quantity="1"/>
		</equips>
		<ai>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="archer"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="oni kapłan">
		<type class="stendhal/oni" subclass="oni_priest" tileid="oni.png:2"/>
		<description>Oto oni kapłan mówiący dziwne zaklęcia.</description>
		<attributes>
			<atk value="547"/>
			<def value="76"/>
			<hp value="680"/>
			<speed value="0.8"/>
			<size value="1,1"/>
		</attributes>
		<level value="77"/>
		<experience value="5290"/>
		<respawn value="2590"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="bukłak z wodą" quantity="[1,2]" probability="50.0"/>
			<item value="money" quantity="[10,40]" probability="100.0"/>
			<item value="buty cieni" quantity="[1,1]" probability="0.5"/>
			<item value="płaszcz chaosu" quantity="[1,1]" probability="0.050"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="heal" params="5,40"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="oni król">
		<type class="stendhal/oni" subclass="oni_king" tileid="oni.png:3"/>
		<description>Oto oni król. Jego władza w królestwie pozwala na dowodzenie odważnymi oddziałami oni.</description>
		<attributes>
			<atk value="714"/>
			<def value="93"/>
			<hp value="1200"/>
			<speed value="0.8"/>
			<size value="1,1"/>
		</attributes>
		<level value="109"/>
		<experience value="14000"/>
		<respawn value="5300"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[10,70]" probability="100.0"/>
			<item value="bukłak z wodą" quantity="[1,1]" probability="30.0"/>
			<item value="sztabka złota" quantity="[1,1]" probability="3.0"/>
			<item value="złoty hełm wikingów" quantity="[1,1]" probability="1.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="Stań przede mną, Królem Oni!"/>
			</says>
			<profile name="offensive"/>
			<profile name="human"/>
		</ai>
	</creature>

	<creature name="oni królowa">
		<type class="stendhal/oni" subclass="oni_queen" tileid="oni.png:4"/>
		<description>Oto oni królowa. Wspiera swojego męża i trzyma  pieczę nad królestwem, gdy on zajmuje się podbojem nowych ziem i walką na polach bitewnych.</description>
		<attributes>
			<atk value="737"/>
			<def value="98"/>
			<hp value="1200"/>
			<speed value="0.8"/>
			<size value="1,1"/>
		</attributes>
		<level value="118"/>
		<experience value="17000"/>
		<respawn value="6200"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[10,50]" probability="100.0"/>
			<item value="duży eliksir" quantity="[1,2]" probability="30.0"/>
			<item value="sztabka złota" quantity="[1,2]" probability="5.0"/>
			<item value="złoty płaszcz" quantity="[1,1]" probability="1.0"/>
			<item value="hełm libertyński" quantity="[1,1]" probability="0.1"/>
			<item value="misiurka" quantity="[1,1]" probability="10.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="Ugnij kolana przed Królową Oni."/>
			</says>
			<profile name="offensive"/>
			<profile name="human"/>
		</ai>
	</creature>

	<!-- END: oni -->

</creatures>
