=== KarajuSs/PolskaGRA/data/conf/creatures.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>


<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="stendhal" xmlns:tns="http://www.example.org/creatures"
	elementFormDefault="qualified" xmlns:Q2="stendhal">

	<xsd:element name="creatures" type="Q2:CreaturesType"></xsd:element>

	<xsd:complexType name="CreaturesType">
		<xsd:sequence>
			<xsd:element name="creature" type="Q2:CreatureType"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="CreatureType">
		<xsd:sequence>
			<xsd:element name="type" type="Q2:Type" minOccurs="1" />
			<xsd:element name="hidden" type="xsd:string" minOccurs="0" />
			<xsd:element name="description" type="xsd:string" minOccurs="0" />
			<xsd:element name="attributes" type="Q2:Attributes" minOccurs="1" />
			<xsd:element name="level" type="Q2:Level" minOccurs="1" />
			<xsd:element name="experience" type="Q2:Experience"	minOccurs="1" />
			<xsd:element name="respawn" type="Q2:Respawn" />
			<xsd:element name="blood" type="Q2:Blood" minOccurs="0" />
			<xsd:element name="corpse" type="Q2:Corpse" />
			<xsd:element name="drops" type="Q2:Drops" minOccurs="0" />
			<xsd:element name="slots" type="Q2:Slots" minOccurs="0" />
			<xsd:element name="equips" type="Q2:Equips" minOccurs="0" />
			<xsd:element name="abilities" type="Q2:Abilities" minOccurs="0"/>
			<xsd:element name="ai" type="Q2:Ai" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="condition" type="xsd:string" use="optional" />
	</xsd:complexType>

	<xsd:complexType name="Item">
		<xsd:attribute name="value" type="xsd:string" />
		<xsd:attribute name="quantity" type="xsd:string" />
		<xsd:attribute name="probability" type="xsd:double" />
	</xsd:complexType>

	<xsd:complexType name="Drops">
		<xsd:sequence>
			<xsd:element name="item" type="Q2:Item" minOccurs="0"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Respawn">
		<xsd:sequence>
		</xsd:sequence>
		<xsd:attribute name="value" type="xsd:positiveInteger"/>
	</xsd:complexType>
	
	<xsd:complexType name="Blood">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="Corpse">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="width" type="xsd:positiveInteger"/>
		<xsd:attribute name="height" type="xsd:positiveInteger"/>
		<xsd:attribute name="harmless" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Attributes">
		<xsd:sequence>
			<xsd:element name="atk" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="def" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="hp" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="speed" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:decimal" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="size" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="noise" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="state" type="xsd:string" />
					<xsd:attribute name="value" type="xsd:string" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Ai">
		<xsd:sequence>
			<xsd:element name="says" type="Q2:Says" minOccurs="0" />
			<xsd:element name="profile" type="Q2:Profile" minOccurs="1"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Says">
		<xsd:sequence>
			<xsd:element name="noise" type="Q2:Noise" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="sound" type="Q2:Sound" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="movement" type="Q2:Movement" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="death" type="Q2:Death" minOccurs="0"
			  maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Noise">
		<xsd:attribute name="value" type="xsd:string" />
		<xsd:attribute name="state" type="xsd:string"></xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="Sound">
		<xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Movement">
		<xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>
	
	<xsd:complexType name="Death">
	  <xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Profile">
		<xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="params" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Type">
		<xsd:attribute name="class" type="xsd:string" />
		<xsd:attribute name="subclass" type="xsd:string" />
		<xsd:attribute name="tileid" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Level">
		<xsd:attribute name="value" type="xsd:integer" />
	</xsd:complexType>

	<xsd:complexType name="Experience">
		<xsd:attribute name="value" type="xsd:integer" />
	</xsd:complexType>

	<xsd:complexType name="Slots">
		<xsd:sequence>
			<xsd:element name="slot" type="xsd:string" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Equips">
		<xsd:sequence>
			<xsd:element name="slot" type="Q2:Slot" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Abilities">
		<xsd:sequence>
			<xsd:element name="damage" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string" default="cut"/>
					<xsd:attribute name="rangedType" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="susceptibility" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string" />
					<xsd:attribute name="value" type="xsd:decimal" />
				</xsd:complexType>
			</xsd:element>
      <xsd:element name="statusattack" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:attribute name="type" type="xsd:string" />
          <xsd:attribute name="value" type="xsd:decimal" />
        </xsd:complexType>
      </xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Slot">
	    <xsd:sequence>
	    </xsd:sequence>
	    <xsd:attribute name="name" type="xsd:string" use="required" />
	    <xsd:attribute name="item" type="xsd:string" use="required" />
	    <xsd:attribute name="quantity" type="xsd:positiveInteger" />
	</xsd:complexType>

</xsd:schema>

=== KarajuSs/PolskaGRA/data/conf/creatures/pol/zjawy.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../creatures.xsd ">

	<!-- START: zjawy -->

	<creature name="szkielet uzbrojony">
		<type class="pol/zjawy" subclass="szkielet_waleczny" tileid="pol_zjawy.png:0"/>
		<description/>
		<attributes>
			<atk value="174"/>
			<def value="24"/>
			<hp value="90"/>
			<speed value="0.5"/>
			<size value="1,1"/>
			<resistance value="100"/>
			<visibility value="100"/>
		</attributes>
		<level value="23"/>
		<experience value="350"/>
		<respawn value="980"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[5,29]" probability="100.0"/>
			<item value="złota kolczuga" quantity="[1,1]" probability="1.0"/>
			<item value="zardzewiała zbroja płytowa" quantity="[1,1]" probability="15.5"/>
			<item value="kość dla psa" quantity="[1,1]" probability="20.0"/>
			<item value="tarcza z czaszką" quantity="[1,1]" probability="0.12"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<noise state="idle follow fight" value="Powiadam ci, nie zabijesz w nas ducha!"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="boginka">
		<type class="pol/zjawy" subclass="boginka" tileid="pol_zjawy.png:1"/>
		<description/>
		<attributes>
			<atk value="451"/>
			<def value="67"/>
			<hp value="952"/>
			<speed value="0.9"/>
			<size value="1,1"/>
			<resistance value="100"/>
			<visibility value="100"/>
		</attributes>
		<level value="131"/>
		<experience value="5999"/>
		<respawn value="1999"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="rękawice cieni" quantity="[1,1]" probability="0.00025"/>
			<item value="pluszowy miś" quantity="[1,1]" probability="25.0"/>
			<item value="straszna dynia" quantity="[1,1]" probability="5.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="strzyga polna">
		<type class="pol/zjawy" subclass="strzyga_polna" tileid="pol_zjawy.png:2"/>
		<description/>
		<attributes>
			<atk value="244"/>
			<def value="30"/>
			<hp value="240"/>
			<speed value="1.0"/>
			<size value="1,1"/>
			<resistance value="100"/>
			<visibility value="100"/>
		</attributes>
		<level value="23"/>
		<experience value="2345"/>
		<respawn value="1410"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[5,20]" probability="100.0"/>
			<item value="zbroja światła" quantity="[1,1]" probability="0.005"/>
			<item value="lazurowe rękawice" quantity="[1,1]" probability="0.0025"/>
			<item value="płaszcz elficki" quantity="[1,1]" probability="0.5"/>
			<item value="półtorak" quantity="[1,1]" probability="0.005"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<sound value="evillaugh-5"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="strzyga leśna">
		<type class="pol/zjawy" subclass="strzyga_lesna" tileid="pol_zjawy.png:3"/>
		<description/>
		<attributes>
			<atk value="266"/>
			<def value="33"/>
			<hp value="440"/>
			<speed value="1.0"/>
			<size value="1,1"/>
			<resistance value="100"/>
			<visibility value="100"/>
		</attributes>
		<level value="33"/>
		<experience value="2585"/>
		<respawn value="1141"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[5,50]" probability="100.0"/>
			<item value="polska tarcza kolcza" quantity="[1,1]" probability="1.5"/>
			<item value="polska tarcza ciężka" quantity="[1,1]" probability="0.01"/>
			<item value="polska tarcza lekka" quantity="[1,1]" probability="0.05"/>
			<item value="polska płytowa tarcza" quantity="[1,1]" probability="1.0"/>
			<item value="polska tarcza drewniana" quantity="[1,1]" probability="10.0"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<sound value="evillaugh-5"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="leśna zjawa">
		<type class="pol/zjawy" subclass="lesna_zjawa" tileid="pol_zjawy.png:4"/>
		<description/>
		<attributes>
			<atk value="166"/>
			<def value="66"/>
			<hp value="666"/>
			<speed value="0.9"/>
			<size value="1,1"/>
			<resistance value="50"/>
			<visibility value="50"/>
		</attributes>
		<level value="111"/>
		<experience value="666"/>
		<respawn value="666"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[1,1]" probability="100.0"/>
			<item value="żelazo" quantity="[1,1]" probability="0.005"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<noise state="idle follow fight" value="Zbłądziłeś rycerzu? Wyprowadzę cię stąd..."/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="zjawa">
		<type class="pol/zjawy" subclass="zjawa_czarna" tileid="pol_zjawy.png:5"/>
		<description/>
		<attributes>
			<atk value="618"/>
			<def value="58"/>
			<hp value="3224"/>
			<speed value="0.5"/>
			<size value="1,1"/>
			<resistance value="50"/>
			<visibility value="50"/>
		</attributes>
		<level value="62"/>
		<experience value="1920"/>
		<respawn value="2520"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="czarny sztylet" quantity="[1,1]" probability="0.0025"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<noise state="idle follow fight" value="Przebacz Brunhildo!"/>
			</says>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="heal" params="5,50"/>
		</ai>
	</creature>

	<creature name="zjawa Brunhildy">
		<type class="pol/zjawy" subclass="zjawa_brunhilda" tileid="pol_zjawy.png:6"/>
		<description/>
		<attributes>
			<atk value="923"/>
			<def value="61"/>
			<hp value="8384"/>
			<speed value="0.5"/>
			<size value="1,1"/>
			<resistance value="50"/>
			<visibility value="50"/>
		</attributes>
		<level value="101"/>
		<experience value="5343"/>
		<respawn value="2686"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[1,80]" probability="100.0"/>
			<item value="korale" quantity="[1,1]" probability="12.0"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<noise state="idle follow fight" value="Nie przebaczę!"/>
				<noise state="idle follow fight" value="Nigdy nie przebaczę!"/>
			</says>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="heal" params="5,50"/>
		</ai>
	</creature>

	<creature name="kostucha">
		<type class="pol/zjawy" subclass="zai_kostucha" tileid="pol_zjawy.png:7"/>
		<description/>
		<attributes>
			<atk value="698"/>
			<def value="69"/>
			<hp value="3818"/>
			<speed value="1.0"/>
			<size value="1,1"/>
			<resistance value="100"/>
			<visibility value="100"/>
		</attributes>
		<level value="340"/>
		<experience value="65432"/>
		<respawn value="18600"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[1,999]" probability="50.0"/>
			<item value="duży eliksir" quantity="[1,5]" probability="30.0"/>
			<item value="czarne rękawice" quantity="[1,1]" probability="0.0005"/>
			<item value="płaszcz z otchłani" quantity="[1,1]" probability="1.0"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<noise state="idle follow fight" value="Jednym cięciem twą głowę zdejmę! Założysz się?!"/>
			</says>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="heal" params="5,50"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="kostucha różowa">
		<type class="pol/zjawy" subclass="zai_kostucha_rozowa" tileid="pol_zjawy.png:8"/>
		<description/>
		<attributes>
			<atk value="808"/>
			<def value="73"/>
			<hp value="3318"/>
			<speed value="1.0"/>
			<size value="1,1"/>
			<resistance value="100"/>
			<visibility value="100"/>
		</attributes>
		<level value="380"/>
		<experience value="67890"/>
		<respawn value="19600"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[1,666]" probability="50.0"/>
			<item value="duży eliksir" quantity="[1,2]" probability="30.0"/>
			<item value="płaszcz licha" quantity="[1,1]" probability="0.5"/>
			<item value="tarcza licha" quantity="[1,1]" probability="2.5"/>
			<item value="kosa pordzewiała" quantity="[1,1]" probability="2.5"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<noise state="idle follow fight" value="Always look for the bright side of... death!"/>
			</says>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="heal" params="5,50"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="żywioł nicości">
		<type class="pol/zjawy" subclass="shadow_elemental" tileid="pol_zjawy.png:9"/>
		<description/>
		<attributes>
			<atk value="441"/>
			<def value="74"/>
			<hp value="380"/>
			<speed value="1.0"/>
			<size value="1,1"/>
			<resistance value="100"/>
			<visibility value="75"/>
		</attributes>
		<level value="55"/>
		<experience value="1850"/>
		<respawn value="1960"/>
		<corpse name="other"/>
		<drops>
			<item value="money" quantity="[5,40]" probability="100.0"/>
			<item value="mocne antidotum" quantity="[1,9]" probability="20.0"/>
			<item value="miecz cieni" quantity="[1,1]" probability="1.1"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<!-- END: zjawy -->

</creatures>

=== KarajuSs/PolskaGRA/data/conf/creatures/pol/kamienne.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../../creatures.xsd ">

	<!-- START: kamienne -->

	<creature name="kamień">
		<type class="pol/kamienne" subclass="kamien" tileid="pol_kamienne.png:0"/>
		<attributes>
			<atk value="97"/>
			<def value="97"/>
			<hp value="12"/>
			<speed value="0.3"/>
			<size value="1,1"/>
		</attributes>
		<level value="20"/>
		<experience value="280"/>
		<respawn value="9600"/>
		<corpse name="rocks"/>
		<drops>
			<item value="kamienie" quantity="[1,2]" probability="100.0"/>
			<item value="kamyk" quantity="[1,19]" probability="100.0"/>
			<item value="buty kamienne" quantity="[1,1]" probability="0.0001"/>
			<item value="płaszcz kamienny" quantity="[1,1]" probability="0.0001"/>
			<item value="kamienna tarcza" quantity="[1,1]" probability="0.5"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<sound value="pol-stones2"/>
			</says>
			<profile name="brave"/>
			<profile name="animal"/>
			<profile name="offensive"/>
		</ai>
	</creature>

	<creature name="wieża">
		<type class="pol/kamienne" subclass="wieza" tileid="pol_kamienne.png:1"/>
		<attributes>
			<atk value="750"/>
			<def value="375"/>
			<hp value="10285"/>
			<speed value="0.2"/>
			<size value="2,2"/>
		</attributes>
		<level value="200"/>
		<experience value="10920"/>
		<respawn value="13449"/>
		<corpse name="giant_rocks"/>
		<drops>
			<item value="kamienie" quantity="[1,9]" probability="100.0"/>
			<item value="kamyk" quantity="[1,39]" probability="100.0"/>
			<item value="buty kamienne" quantity="[1,1]" probability="5.0"/>
			<item value="płaszcz kamienny" quantity="[1,1]" probability="2.0"/>
			<item value="kamienna tarcza" quantity="[1,1]" probability="5.0"/>
			<item value="kamienna zbroja" quantity="[1,1]" probability="1.0"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<sound value="pol-giant"/>
			</says>
			<profile name="brave"/>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="rare"/>
		</ai>
	</creature>

	<!-- END: kamienne -->

</creatures>

=== KarajuSs/PolskaGRA/data/conf/creatures/pol/zbojnicy_gorscy.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../creatures.xsd ">

	<!-- START: zbojnicy gorscy -->

	<creature name="zbójnik górski">
		<type class="pol/zbojnicy_gorscy" subclass="zbojnik_gorski" tileid="pol_zbojnicy_gorscy.png:0"/>
		<description>Oto zbójnik górski, który kryje się w jaskiniach.</description>
		<attributes>
			<atk value="250"/>
			<def value="49"/>
			<hp value="290"/>
			<speed value="0.8"/>
			<size value="1,1"/>
		</attributes>
		<level value="59"/>
		<experience value="3110"/>
		<respawn value="3110"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[9,29]" probability="100.0"/>
			<item value="ciupaga" quantity="[1,1]" probability="0.5"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="zbójnik górski goniec">
		<type class="pol/zbojnicy_gorscy" subclass="zbojnik_gorski_goniec" tileid="pol_zbojnicy_gorscy.png:1"/>
		<description>Oto zbójnik górski goniec, który donosi o wszystkim hersztowi.</description>
		<attributes>
			<atk value="290"/>
			<def value="52"/>
			<hp value="333"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="60"/>
		<experience value="3330"/>
		<respawn value="3110"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[9,10]" probability="100.0"/>
			<item value="ciupaga" quantity="[1,1]" probability="1.005"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="zbójnik górski złośliwy">
		<type class="pol/zbojnicy_gorscy" subclass="zbojnik_gorski_zlosliwy" tileid="pol_zbojnicy_gorscy.png:2"/>
		<description>Oto zbójnik górski złośliwy, który chociaż gruby atakuje zwinnie.</description>
		<attributes>
			<atk value="390"/>
			<def value="53"/>
			<hp value="309"/>
			<speed value="0.7"/>
			<size value="1,1"/>
		</attributes>
		<level value="62"/>
		<experience value="3630"/>
		<respawn value="3110"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[9,99]" probability="100.0"/>
			<item value="ciupaga" quantity="[1,1]" probability="1.5"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="zbójnik górski zwiadowca">
		<type class="pol/zbojnicy_gorscy" subclass="zbojnik_gorski_zwiadowca" tileid="pol_zbojnicy_gorscy.png:3"/>
		<description>Oto zbójnik górski zwiadowca, który atakuje cicho i nagle.</description>
		<attributes>
			<atk value="330"/>
			<def value="54"/>
			<hp value="345"/>
			<speed value="0.9"/>
			<size value="1,1"/>
		</attributes>
		<level value="63"/>
		<experience value="3530"/>
		<respawn value="3110"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[9,99]" probability="100.0"/>
			<item value="ciupaga" quantity="[1,1]" probability="1.005"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="zbójnik górski starszy">
		<type class="pol/zbojnicy_gorscy" subclass="zbojnik_gorski_starszy" tileid="pol_zbojnicy_gorscy.png:4"/>
		<description>Oto zbójnik górski starszy, który chociaż brodę ma siwą zręcznie włada maczugą.</description>
		<attributes>
			<atk value="410"/>
			<def value="51"/>
			<hp value="290"/>
			<speed value="0.5"/>
			<size value="1,1"/>
		</attributes>
		<level value="64"/>
		<experience value="3630"/>
		<respawn value="3110"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[9,99]" probability="100.0"/>
			<item value="futro" quantity="[1,1]" probability="10.0"/>
			<item value="ciupaga" quantity="[1,1]" probability="1.005"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="zbójnik górski herszt">
		<type class="pol/zbojnicy_gorscy" subclass="zbojnik_gorski_herszt" tileid="pol_zbojnicy_gorscy.png:5"/>
		<description>Oto herszt zbójników górskich, którego zła sława dotarła daleko poza granice tej krainy.</description>
		<attributes>
			<atk value="440"/>
			<def value="58"/>
			<hp value="490"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="66"/>
		<experience value="3830"/>
		<respawn value="6110"/>
		<corpse name="human"/>
		<drops>
			<item value="pióro herszta hordy zbójeckiej" quantity="[1,1]" probability="100.0"/>
			<item value="money" quantity="[9,99]" probability="100.0"/>
			<item value="ciupaga" quantity="[1,1]" probability="8.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<!-- END: zbojnicy gorscy -->

</creatures>
