=== KarajuSs/PolskaGRA/data/conf/creatures.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>


<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="stendhal" xmlns:tns="http://www.example.org/creatures"
	elementFormDefault="qualified" xmlns:Q2="stendhal">

	<xsd:element name="creatures" type="Q2:CreaturesType"></xsd:element>

	<xsd:complexType name="CreaturesType">
		<xsd:sequence>
			<xsd:element name="creature" type="Q2:CreatureType"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="CreatureType">
		<xsd:sequence>
			<xsd:element name="type" type="Q2:Type" minOccurs="1" />
			<xsd:element name="hidden" type="xsd:string" minOccurs="0" />
			<xsd:element name="description" type="xsd:string" minOccurs="0" />
			<xsd:element name="attributes" type="Q2:Attributes" minOccurs="1" />
			<xsd:element name="level" type="Q2:Level" minOccurs="1" />
			<xsd:element name="experience" type="Q2:Experience"	minOccurs="1" />
			<xsd:element name="respawn" type="Q2:Respawn" />
			<xsd:element name="blood" type="Q2:Blood" minOccurs="0" />
			<xsd:element name="corpse" type="Q2:Corpse" />
			<xsd:element name="drops" type="Q2:Drops" minOccurs="0" />
			<xsd:element name="slots" type="Q2:Slots" minOccurs="0" />
			<xsd:element name="equips" type="Q2:Equips" minOccurs="0" />
			<xsd:element name="abilities" type="Q2:Abilities" minOccurs="0"/>
			<xsd:element name="ai" type="Q2:Ai" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="condition" type="xsd:string" use="optional" />
	</xsd:complexType>

	<xsd:complexType name="Item">
		<xsd:attribute name="value" type="xsd:string" />
		<xsd:attribute name="quantity" type="xsd:string" />
		<xsd:attribute name="probability" type="xsd:double" />
	</xsd:complexType>

	<xsd:complexType name="Drops">
		<xsd:sequence>
			<xsd:element name="item" type="Q2:Item" minOccurs="0"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Respawn">
		<xsd:sequence>
		</xsd:sequence>
		<xsd:attribute name="value" type="xsd:positiveInteger"/>
	</xsd:complexType>
	
	<xsd:complexType name="Blood">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="Corpse">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="width" type="xsd:positiveInteger"/>
		<xsd:attribute name="height" type="xsd:positiveInteger"/>
		<xsd:attribute name="harmless" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Attributes">
		<xsd:sequence>
			<xsd:element name="atk" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="def" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="hp" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="speed" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:decimal" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="size" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="noise" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="state" type="xsd:string" />
					<xsd:attribute name="value" type="xsd:string" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Ai">
		<xsd:sequence>
			<xsd:element name="says" type="Q2:Says" minOccurs="0" />
			<xsd:element name="profile" type="Q2:Profile" minOccurs="1"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Says">
		<xsd:sequence>
			<xsd:element name="noise" type="Q2:Noise" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="sound" type="Q2:Sound" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="movement" type="Q2:Movement" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="death" type="Q2:Death" minOccurs="0"
			  maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Noise">
		<xsd:attribute name="value" type="xsd:string" />
		<xsd:attribute name="state" type="xsd:string"></xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="Sound">
		<xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Movement">
		<xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>
	
	<xsd:complexType name="Death">
	  <xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Profile">
		<xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="params" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Type">
		<xsd:attribute name="class" type="xsd:string" />
		<xsd:attribute name="subclass" type="xsd:string" />
		<xsd:attribute name="tileid" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Level">
		<xsd:attribute name="value" type="xsd:integer" />
	</xsd:complexType>

	<xsd:complexType name="Experience">
		<xsd:attribute name="value" type="xsd:integer" />
	</xsd:complexType>

	<xsd:complexType name="Slots">
		<xsd:sequence>
			<xsd:element name="slot" type="xsd:string" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Equips">
		<xsd:sequence>
			<xsd:element name="slot" type="Q2:Slot" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Abilities">
		<xsd:sequence>
			<xsd:element name="damage" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string" default="cut"/>
					<xsd:attribute name="rangedType" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="susceptibility" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string" />
					<xsd:attribute name="value" type="xsd:decimal" />
				</xsd:complexType>
			</xsd:element>
      <xsd:element name="statusattack" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:attribute name="type" type="xsd:string" />
          <xsd:attribute name="value" type="xsd:decimal" />
        </xsd:complexType>
      </xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Slot">
	    <xsd:sequence>
	    </xsd:sequence>
	    <xsd:attribute name="name" type="xsd:string" use="required" />
	    <xsd:attribute name="item" type="xsd:string" use="required" />
	    <xsd:attribute name="quantity" type="xsd:positiveInteger" />
	</xsd:complexType>

</xsd:schema>

=== KarajuSs/PolskaGRA/data/conf/creatures/stendhal/troll.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../../creatures.xsd ">

	<!-- START: cyclops -->

	<creature name="cyklop">
		<type class="stendhal/giant" subclass="cyclops" tileid="giant.png:0"/>
		<description>Widzisz cyklopa. On widzi cię nieco gorzej, bo ma jedno oko.</description>
		<attributes>
			<atk value="125"/>
			<def value="26"/>
			<hp value="60"/>
			<speed value="0.5"/>
			<size value="1,1"/>
		</attributes>
		<level value="9"/>
		<experience value="90"/>
		<respawn value="1200"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[6,13]" probability="100.0"/>
			<item value="kolczuga" quantity="[1,1]" probability="1.0"/>
			<item value="skórzany kirys" quantity="[1,1]" probability="10.0"/>
			<item value="buty nabijane ćwiekami" quantity="[1,1]" probability="0.5"/>
			<item value="piernacz" quantity="[1,1]" probability="1.0"/>
			<item value="tarcza ćwiekowa" quantity="[1,1]" probability="0.5"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<sound value="yell-1"/>
				<sound value="laugh-33"/>
				<sound value="laugh-evil-4"/>
				<sound value="evillaugh-4"/>
				<sound value="grunt-1"/>
				<sound value="grunt-2"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<!-- END: cyclops -->

	<!-- START: ogre -->

	<creature name="ogr">
		<type class="stendhal/giant" subclass="ogre" tileid="giant.png:2"/>
		<description>To jest ogr. Jest goły i ordynarny.</description>
		<attributes>
			<atk value="151"/>
			<def value="20"/>
			<hp value="140"/>
			<speed value="0.6"/>
			<size value="1,1"/>
		</attributes>
		<level value="12"/>
		<experience value="130"/>
		<respawn value="1210"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[6,19]" probability="100.0"/>
			<item value="pyrlik" quantity="[1,1]" probability="7.0"/>
			<item value="złoty pyrlik" quantity="[1,1]" probability="0.7"/>
			<item value="kolczuga" quantity="[1,1]" probability="10.0"/>
			<item value="zbroja łuskowa" quantity="[1,1]" probability="0.9"/>
			<item value="piernacz" quantity="[1,1]" probability="0.9"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<sound value="yell-1"/>
				<sound value="groan-1"/>
				<sound value="moan-1"/>
				<sound value="fart-1"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="ogr starszy">
		<type class="stendhal/giant" subclass="elder_ogre" tileid="giant.png:1"/>
		<description>Oto ogr starszy. Zostały mu ostatnie minuty zycia. Zmiłuj się nad nim.</description>
		<attributes>
			<atk value="195"/>
			<def value="13"/>
			<hp value="350"/>
			<speed value="0.6"/>
			<size value="1,1"/>
		</attributes>
		<level value="17"/>
		<experience value="210"/>
		<respawn value="1240"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[6,27]" probability="100.0"/>
			<item value="zbroja łuskowa" quantity="[1,1]" probability="4.0"/>
			<item value="żelazna zbroja łuskowa" quantity="[1,1]" probability="1.0"/>
			<item value="kij z czaszką" quantity="[1,1]" probability="1.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<sound value="yell-1"/>
				<sound value="groan-1"/>
				<sound value="moan-1"/>
				<sound value="fart-1"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="ogr żołnierz">
		<type class="stendhal/giant" subclass="ogre_soldier" tileid="giant.png:3"/>
		<description>Oto ogr żołnierz. Śmierdzi jakby nie brał kąpieli od roku. Łeee.</description>
		<attributes>
			<atk value="222"/>
			<def value="40"/>
			<hp value="132"/>
			<speed value="0.6"/>
			<size value="1,1"/>
		</attributes>
		<level value="22"/>
		<experience value="320"/>
		<respawn value="1270"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[6,31]" probability="100.0"/>
			<item value="topór bojowy" quantity="[1,1]" probability="2.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<sound value="yell-1"/>
				<sound value="groan-1"/>
				<sound value="moan-1"/>
				<sound value="fart-1"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="superogr">
		<type class="stendhal/giant" subclass="superogre" tileid="giant.png:4"/>
		<description>Oto superogr, który jest członkiem przyziemnej rodziny Ogrów. Nim to się stało ten szczególny hełm był wśród nich czczony. Uważaj potrafi uderzyć!</description>
		<attributes>
			<atk value="296"/>
			<def value="52"/>
			<hp value="195"/>
			<speed value="0.6"/>
			<size value="1,1"/>
		</attributes>
		<level value="33"/>
		<experience value="640"/>
		<respawn value="1380"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[6,31]" probability="100.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<sound value="yell-1"/>
				<sound value="groan-1"/>
				<sound value="moan-1"/>
				<sound value="fart-1"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
		</ai>
	</creature>

  <!-- END: ogre -->
  
  <!-- START: troll -->

	<creature name="trol">
		<type class="stendhal/troll" subclass="troll" tileid="troll.png:0"/>
		<description>To jest trol. Uważaj, bo jesteś na jego ziemi.</description>
		<attributes>
			<atk value="135"/>
			<def value="34"/>
			<hp value="60"/>
			<speed value="0.5"/>
			<size value="1,1"/>
		</attributes>
		<level value="10"/>
		<experience value="110"/>
		<respawn value="1210"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[3,7]" probability="90.0"/>
			<item value="kolczuga" quantity="[1,1]" probability="3.0"/>
			<item value="spodnie kolcze" quantity="[1,1]" probability="2.0"/>
			<item value="kolczuga wzmocniona" quantity="[1,1]" probability="0.05"/>
			<item value="kiścień" quantity="[1,1]" probability="30.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<sound value="gorilla-1"/>
				<sound value="gorilla-2"/>
				<sound value="gorilla-3"/>
				<sound value="gorilla-4"/>
				<sound value="gorilla-5"/>
			</says>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="czerwony trol">
		<type class="stendhal/troll" subclass="red_troll" tileid="troll.png:2"/>
		<description>Oto czerwony trol. Bucha wściekłością.</description>
		<attributes>
			<atk value="190"/>
			<def value="34"/>
			<hp value="110"/>
			<speed value="0.7"/>
			<size value="1,1"/>
		</attributes>
		<level value="16"/>
		<experience value="200"/>
		<respawn value="1230"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[3,17]" probability="90.0"/>
			<item value="zbroja łuskowa" quantity="[1,1]" probability="3.0"/>
			<item value="spodnie kolcze" quantity="[1,1]" probability="4.0"/>
			<item value="kiścień" quantity="[1,1]" probability="30.0"/>
			<item value="kropacz" quantity="[1,1]" probability="0.0001"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<sound value="gorilla-1"/>
				<sound value="gorilla-2"/>
				<sound value="gorilla-3"/>
				<sound value="gorilla-4"/>
				<sound value="gorilla-5"/>
			</says>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="trol jaskiniowy">
		<type class="stendhal/troll" subclass="cave_troll" tileid="troll.png:1"/>
		<description></description>
		<attributes>
			<atk value="474"/>
			<def value="45"/>
			<hp value="1000"/>
			<speed value="0.7"/>
			<size value="2,2"/>
		</attributes>
		<level value="63"/>
		<experience value="3100"/>
		<respawn value="1870"/>
		<corpse name="giant_humanoid" width="2" height="2"/>
		<drops>
			<item value="money" quantity="[1,30]" probability="100.0"/>
			<item value="mięso" quantity="[1,5]" probability="10.5"/>
			<item value="kropacz" quantity="[1,1]" probability="0.0001"/>
			<item value="zbroja barbarzyńcy" quantity="[1,1]" probability="5.5"/>
			<item value="buty kamienne" quantity="[1,1]" probability="2.5"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="Uggga yggga arghhhhh"/>
				<noise state="idle follow fight" value="Ooggga UGGga arhhh"/>
				<sound value="growl-large-3" />
				<sound value="grunt-large-1" />
				<sound value="grunt-large-2" />
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<!-- END: troll -->

</creatures>

=== KarajuSs/PolskaGRA/data/conf/creatures/pol/kamienne_wielkie.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../creatures.xsd ">

	<!-- START: kamienne wielkie -->

	<creature name="głaz">
		<type class="pol/kamienne_wielkie" subclass="glaz" tileid="pol_kamienne_wielkie.png:0"/>
		<attributes>
			<atk value="140"/>
			<def value="140"/>
			<hp value="25"/>
			<speed value="0.5"/>
			<size value="2,2"/>
		</attributes>
		<level value="40"/>
		<experience value="540"/>
		<respawn value="12200"/>
		<corpse name="giant_rocks"/>
		<drops>
			<item value="kamienie" quantity="[1,3]" probability="100.0"/>
			<item value="kamyk" quantity="[1,59]" probability="100.0"/>
			<item value="buty kamienne" quantity="[1,1]" probability="0.5"/>
			<item value="płaszcz kamienny" quantity="[1,1]" probability="0.5"/>
			<item value="kamienna tarcza" quantity="[1,1]" probability="1.0"/>
			<item value="kamienna zbroja" quantity="[1,1]" probability="0.1"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<sound value="pol-stones2"/>
			</says>
			<profile name="brave"/>
			<profile name="animal"/>
			<profile name="offensive"/>
		</ai>
	</creature>

	<creature name="lawina kamienna">
		<type class="pol/kamienne_wielkie" subclass="lawina_kamienna" tileid="pol_kamienne_wielkie.png:1"/>
		<attributes>
			<atk value="3000"/>
			<def value="700"/>
			<hp value="2000"/>
			<speed value="0.9"/>
			<size value="2,2"/>
			<resistance value="50"/>
		</attributes>
		<level value="400"/>
		<experience value="35920"/>
		<respawn value="128200"/>
		<corpse name="giant_rocks"/>
		<drops>
			<item value="kamyk" quantity="[1,39]" probability="100.0"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<sound value="pol-stones2"/>
			</says>
			<profile name="brave"/>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="rare"/>
		</ai>
	</creature>

	<creature name="olbrzymia wieża">
		<type class="pol/kamienne_wielkie" subclass="wieza_olbrzymia" tileid="pol_kamienne_wielkie.png:2"/>
		<attributes>
			<atk value="2523"/>
			<def value="750"/>
			<hp value="20000"/>
			<speed value="0.1"/>
			<size value="4,3"/>
		</attributes>
		<level value="300"/>
		<experience value="20920"/>
		<respawn value="26898"/>
		<corpse name="giant_rocks"/>
		<drops>
			<item value="kamienie" quantity="[1,19]" probability="100.0"/>
			<item value="kamyk" quantity="[1,69]" probability="100.0"/>
			<item value="buty kamienne" quantity="[1,1]" probability="5.0"/>
			<item value="płaszcz kamienny" quantity="[1,1]" probability="5.0"/>
			<item value="kamienna tarcza" quantity="[1,1]" probability="5.0"/>
			<item value="kamienna zbroja" quantity="[1,1]" probability="9.0"/>
			<item value="spodnie kamienne" quantity="[1,1]" probability="1.0"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<sound value="pol-giant"/>
			</says>
			<profile name="brave"/>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="rare"/>
		</ai>
	</creature>

	<!-- END: kamienne wielkie -->

</creatures>

=== KarajuSs/PolskaGRA/data/conf/creatures/pol/beast.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../../creatures.xsd ">

	<!-- START: mutanty -->
	<creature name="dziub dziub">
		<type class="pol/mutanty" subclass="dziub_dziub" tileid="pol_mutanty.png:0"/>
		<description>Oto Dziub-Dziub. Właśnie do zobaczyłeś, więc nie zadawaj głupich pytań.</description>
		<attributes>
			<atk value="20"/>
			<def value="4"/>
			<hp value="22"/>
			<speed value="0.8"/>
			<size value="1,1"/>
		</attributes>
		<level value="3"/>
		<experience value="30"/>
		<respawn value="222"/>
		<corpse name="small_animal"/>
		<drops>
			<item value="dziub ptaka" quantity="[1,1]" probability="0.5"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<noise state="idle follow fight" value="Mam dzioba czy dziób?"/>
				<noise state="idle follow fight" value="Czy ja fruwam, czy latam?"/>
			</says>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="coward"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="wilczykruk">
		<type class="pol/mutanty" subclass="wilczykruk" tileid="pol_mutanty.png:1"/>
		<description/>
		<attributes>
			<atk value="673"/>
			<def value="46"/>
			<hp value="713"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="99"/>
		<experience value="9610"/>
		<respawn value="666"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[1,3]" probability="100.0"/>
			<item value="butelka wody" quantity="[1,3]" probability="20.0"/>
			<item value="kieł wilczy" quantity="[1,1]" probability="100.0"/>
			<item value="pazury wilcze" quantity="[1,5]" probability="100.0"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<noise state="idle follow fight" value="Wrrrrrr!"/>
				<noise state="idle follow fight" value="Hauuuuu!"/>
				<noise state="idle follow fight" value="Auuuu!"/>
				<sound value="pol-growl"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="cerber">
		<type class="pol/mutanty" subclass="cerber" tileid="pol_mutanty.png:2"/>
		<description>Oto cerber - strażnik ogni piekielnych. Jego wzrok wypala piętno na twej duszy.</description>
		<attributes>
			<atk value="476"/>
			<def value="38"/>
			<hp value="504"/>
			<speed value="0.9"/>
			<size value="2,1"/>
		</attributes>
		<level value="70"/>
		<experience value="4933"/>
		<respawn value="99999"/>
		<corpse name="animal"/>
		<drops>
			<item value="money" quantity="[1,1]" probability="100.0"/>
			<item value="stek" quantity="[1,19]" probability="80.0"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<noise state="idle follow fight" value="Rrraar!"/>
				<sound value="pol-growl"/>
			</says>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="patrolling"/>
			<profile name="heal" params="5,30"/>
		</ai>
	</creature>

	<creature name="zółty glut">
		<type class="pol/mutanty" subclass="yellow_slime" tileid="pol_mutanty.png:3"/>
		<description>Oto żółty glut. Za nim kleisty ślad.</description>
		<attributes>
			<atk value="966"/>
			<def value="56"/>
			<hp value="1022"/>
			<speed value="0.6"/>
			<size value="1,1"/>
		</attributes>
		<level value="142"/>
		<experience value="21492"/>
		<respawn value="42187"/>
		<corpse name="other"/>
		<drops>
			<item value="money" quantity="[9,209]" probability="100.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="czerwony glut">
		<type class="pol/mutanty" subclass="red_slime" tileid="pol_mutanty.png:4"/>
		<description>Oto czerwony glut. Za nim kleisty ślad.</description>
		<attributes>
			<atk value="1340"/>
			<def value="67"/>
			<hp value="1418"/>
			<speed value="0.6"/>
			<size value="1,1"/>
		</attributes>
		<level value="197"/>
		<experience value="40727"/>
		<respawn value="75216"/>
		<corpse name="other"/>
		<drops>
			<item value="money" quantity="[99,239]" probability="100.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>
	<!-- END: mutanty -->
	
	<!-- START: mutanty wielkie -->
	<creature name="Jožin z lesa">
		<type class="pol/mutanty_wielkie" subclass="jozin_z_lesa" tileid="pol_mutanty_wielkie.png:0"/>
		<description/>
		<attributes>
			<atk value="605"/>
			<def value="43"/>
			<hp value="641"/>
			<speed value="0.9"/>
			<size value="2,2"/>
		</attributes>
		<level value="89"/>
		<experience value="7826"/>
		<respawn value="1818"/>
		<corpse name="giant"/>
		<drops>
			<item value="money" quantity="[5,40]" probability="100.0"/>
			<item value="mocna trucizna" quantity="[1,2]" probability="5.0"/>
			<item value="buty mainiocyjskie" quantity="[1,1]" probability="0.005"/>
			<item value="nakrapiane jajo" quantity="[1,1]" probability="0.05"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<noise state="idle follow fight" value="tere fere"/>
				<noise state="idle follow fight" value="tere fere trele morele"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="heal" params="5,50"/>
			<profile name="patrolling"/>
			<profile name="poisonous" params="5,mocna trucizna"/>
		</ai>
	</creature>

	<creature name="Jožin z bažin">
		<type class="pol/mutanty_wielkie" subclass="jozin_z_bazin" tileid="pol_mutanty_wielkie.png:1"/>
		<description/>
		<attributes>
			<atk value="666"/>
			<def value="46"/>
			<hp value="706"/>
			<speed value="0.9"/>
			<size value="2,2"/>
		</attributes>
		<level value="98"/>
		<experience value="9423"/>
		<respawn value="1818"/>
		<corpse name="giant"/>
		<drops>
			<item value="money" quantity="[4,50]" probability="100.0"/>
			<item value="mocna trucizna" quantity="[1,2]" probability="5.0"/>
			<item value="tarcza mainiocyjska" quantity="[1,1]" probability="0.005"/>
			<item value="jajo wielkanocne" quantity="[1,1]" probability="0.05"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<noise state="idle follow fight" value="Jožin z bažin močálem se plíží"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="heal" params="15,50"/>
			<profile name="patrolling"/>
			<profile name="poisonous" params="10,mocna trucizna"/>
		</ai>
	</creature>

	<creature name="coś niszczącego">
		<type class="pol/mutanty_wielkie" subclass="easer_thing" tileid="pol_mutanty_wielkie.png:3"/>
		<description/>
		<attributes>
			<atk value="1870"/>
			<def value="83"/>
			<hp value="3180"/>
			<speed value="1.0"/>
			<size value="2,2"/>
		</attributes>
		<level value="275"/>
		<experience value="132506"/>
		<respawn value="19300"/>
		<corpse name="giant"/>
		<drops>
			<item value="wielki eliksir" quantity="[1,3]" probability="100.0"/>
			<item value="mocne antidotum" quantity="[1,6]" probability="80.0"/>
			<item value="money" quantity="[100,900]" probability="100.0"/>
			<item value="buty z zielonego potwora" quantity="[1,1]" probability="12.5"/>
			<item value="kamienna zbroja" quantity="[1,1]" probability="5.5"/>
			<item value="ząb potwora" quantity="[1,1]" probability="5.5"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="heal" params="15,25"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="gigantyczne monstrum">
		<type class="pol/mutanty_wielkie" subclass="ae_monstrum_gigant" tileid="pol_mutanty_wielkie.png:2"/>
		<description/>
		<attributes>
			<atk value="1353"/>
			<def value="68"/>
			<hp value="2633"/>
			<speed value="1.0"/>
			<size value="2,2"/>
		</attributes>
		<level value="199"/>
		<experience value="42299"/>
		<respawn value="12345"/>
		<corpse name="giant_humanoid"/>
		<drops>
			<item value="wielki eliksir" quantity="[1,3]" probability="50.0"/>
			<item value="money" quantity="[9,999]" probability="100.0"/>
			<item value="rękawice cieni" quantity="[1,1]" probability="1.0"/>
			<item value="miecz cieni" quantity="[1,1]" probability="5.0"/>
		</drops>
		<equips/>
		<ai>
			<says>
				<noise state="idle follow fight" value="Wydaj swój ostatni oddech!"/>
			</says>
			<profile name="brave"/>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="heal" params="15,50"/>
			<profile name="patrolling"/>
		</ai>
	</creature>
	<!-- END: mutanty wielkie -->
</creatures>
